spring.application.name=citizen-query-service

server.port=${PORT:8081}

# DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# REDIS
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=200ms

spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0
spring.data.redis.lettuce.shutdown-timeout=100ms

# CIRCUIT BREAKER
resilience4j.circuitbreaker.instances.redisCache.slidingWindowSize=10
resilience4j.circuitbreaker.instances.redisCache.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.redisCache.failureRateThreshold=50
resilience4j.circuitbreaker.instances.redisCache.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.redisCache.permittedNumberOfCallsInHalfOpenState=3

# SWAGGER
springdoc.api-docs.path=/api/v1/docs
springdoc.swagger-ui.path=/swagger-ui.html

# LOGGING
logging.level.root=INFO
logging.level.com.electoral=DEBUG
logging.level.io.github.resilience4j=DEBUG